name: Deployment to QA Qrg

on:
  push:
    branches:
      - qa
jobs:
  deploy: 
    runs-on: ubuntu-latest

    steps:
      
      - run: echo "🐧 GitHub Action running on ${{ runner.os }}"
      - run: echo "🔎 Retrieving ${{ github.ref }} from ${{ github.repository }}."
      - uses: actions/checkout@v3
      - run: npm install sfdx-cli -g
      - run: echo "${{ vars.SALESFORCE_JWT_SECRET_KEY_QA }}" > server.key
      - run: sfdx auth:jwt:grant -u=${{ vars.SF_USERNAME }}  -f=server.key -i=${{ vars.SF_CLIENT_ID_QA }} -r=${{vars.HUB_LOGIN_URL}}
      - run: sfdx force:source:deploy -p force-app/main/default -u=${{ vars.SF_USERNAME }}
